### ISSUE TITLE
ch7_usertest.c 的44行printf少一个换行

### ISSUE THREAD

**Issue by FztTony** [DeathWish5/riscvos-c-tests#1]
/user/src/ch7_usertest.c的44行
printf("Usertests: Test %s in Process %d exited with code %d", test, pid, xstate);应该为printf("Usertests: Test %s in Process %d exited with code %d\n", test, pid, xstate);
issue一下

**Comment by DeathWish5** [comment]
收到，以后这种修改可以直接发 PR，谢谢。
